docs_dir: docs
site_author: Péter Böröcz
site_description: Blog and reference site for Péter Böröcz
site_dir: deploy
site_name: Flirting with Neutrality
site_url: https://peterborocz.blog
repo_url: https://github.com/PBorocz/public_content
repo_name: 'public_content'
remote_branch: main

nav:
  - Home: 'README.md'

  - Nano:
    - 'posts/nano/index.md'
    - Just vs Makefiles: 'posts/nano/just_vs_makefiles.md'

  - Micro:
    - 'posts/micro/index.md'
    - New on New: 'posts/micro/new_on_new.md'
    - Accrual vs Cash: 'posts/micro/accrual_vs_cash.md'

  - Macro:
    - 'posts/macro/index.md'
    - Long Term Investing: 'posts/macro/investing.md'

  - Projects:
    - 'posts/projects/index.md'
    - Meta-Knowledge: 'posts/projects/knowledge.md'

  - Tech:
    - 'posts/tech/index.md'
    - My Emacs Configuration: 'posts/tech/emacs.md'
    - My Python Environment: 'posts/tech/python.md'

  - Tags: 'misc/tags.md'

  - About: 'misc/about.md'

not_in_nav: |
  /misc/cv.md
  /posts/*/*.md

exclude_docs: |
  .gitignore

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

plugins:
  - search
  - social
  - tags:
      tags_file: 'misc/tags.md'
  - git-revision-date-localized:
      enable_creation_date: false
      fallback_to_build_date: true
      type: date

extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PBorocz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pborocz
    - icon: fontawesome/brands/threads
      link: https://threads.net/@pgborocz
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@BoroczPeter
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/MadHun/

################################################################################
# Configurationfor Material for MkDocs Theme
################################################################################
theme:
  name: material

  icon:
    repo: fontawesome/brands/github
    logo: material/devices

  custom_dir: theme_overrides

  features:
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - content.action.view
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  locale: en

  favicon: assets/images/favicon/favicon.ico

  font: false # Gives us OS System default font.

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: "blue grey"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue grey"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  markdown_extensions:
    - attr_list
    - def_list
    - pymdownx.emoji:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - smarty
    - tables
    - pymdownx.highlight:
        use_pygments: true
        pygments_lang_class: true
        anchor_linenums: true
        line_spans: __span
    - pymdownx.tasklist:
        custom_checkbox: true
